disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Dr.-Ing. Johannes Meyer - Science and Coaching"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

["params.author"]
name = "Dr.-Ing. Johannes Meyer"
image = "sq.png"
