[[main]]
none = "none"



[[main]]
  name = "Publications"
  url = "/publications/"
  weight = 30

[[main]]
  name = "Events"
  pageRef = "events.markdown"
  weight = 40

[[main]]
  name = "Teaching"
  pageRef = "teaching.markdown"
  weight = 50

[[footer]]
none = "none"

[[footer]]
name = "Impressum"
pageRef = "impressum.md"
identifier = "h1tqWQyZ7p"
weight = 9_999

[[footer]]
name = "Datenschutz"
pageRef = "datenschutz.markdown"
identifier = "97v1XdTRYd"
weight = 9_999
