# baseURL = 'https://jojomey87.github.io/page/'
baseURL = 'https://meyerj.de/'
languageCode = 'en-us'
title = 'Johannes Meyer'
[[menus.main]]
  name = "Publications"
  url = "/publications/"
  weight = 30